services:
  fe:
    build:
      context: ./light-weights-fe
    ports:
      - '4200:80'
    networks:
      - lightweights_network


  be:
    build:
      context: ./light-weights-be
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: light-weights
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - lightweights_network


  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=light-weights'
      - 'POSTGRES_PASSWORD=passwd'
      - 'POSTGRES_USER=dbuser'
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - lightweights_network

volumes:
  db_data:

networks:
  lightweights_network:
    driver: bridge
