services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=light-weights'
      - 'POSTGRES_PASSWORD=passwd'
      - 'POSTGRES_USER=dbuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lightweights_network

volumes:
  postgres_data:

networks:
  lightweights_network:
    driver: bridge
