app:
  frontend-url: ${FRONTEND_URL:http://localhost:4200}

security:
  jwt:
    secret-key: VdwxrFd/Q7N3b2/Ej9WrR3HroWSBExNKBHsc6goD/6E=

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:light-weights}
    username: ${DB_USER:dbuser}
    password: ${DB_PASSWORD:passwd}

  jpa:
    show-sql: true
