app:
  frontend-url: ${FRONTEND_URL}

security:
  jwt:
    secret-key: ${JWT_SECRET}

spring:
  profiles.active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: light-weights
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  server:
    port: ${PORT:8080}